In [1]:
import numpy as np

In [5]:
np.array([[1,2,3],[4,5,6]])+np.array([[100],[200]])

array([[101, 102, 103],
       [204, 205, 206]])

In [6]:
np.array([[100],[200]])

array([[100],
       [200]])

In [7]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [8]:
a

array([[-0.80057465,  0.5953875 ,  0.00229179],
       [ 0.32494182, -0.13359796,  1.2744153 ]])

In [9]:
b

array([[-1.56611298],
       [ 0.37753184]])

In [10]:
c.shape

(2, 3)

In [11]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [12]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [13]:
c.shape

(12288, 45)

In [14]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

ValueError: setting an array element with a sequence.

In [15]:
a=np.random.randn(3,4)

In [16]:
a

array([[ 0.01699621,  0.79392535,  1.09385667,  1.33406288],
       [-2.18735172, -0.47923781, -0.45105652, -1.09238602],
       [-1.58118768, -0.56669997,  0.46156883,  0.17550068]])

In [18]:
b=np.random.randn(4,1)

In [19]:
b

array([[ 0.37060991],
       [ 0.04357174],
       [ 0.51715085],
       [-1.76934276]])

In [20]:
a.T

array([[ 0.01699621, -2.18735172, -1.58118768],
       [ 0.79392535, -0.47923781, -0.56669997],
       [ 1.09385667, -0.45105652,  0.46156883],
       [ 1.33406288, -1.09238602,  0.17550068]])

In [ ]:
4X3

In [21]:
b.T

array([[ 0.37060991,  0.04357174,  0.51715085, -1.76934276]])

In [22]:
a.T+b

array([[ 0.38760611, -1.81674181, -1.21057778],
       [ 0.83749709, -0.43566607, -0.52312824],
       [ 1.61100753,  0.06609434,  0.97871968],
       [-0.43527987, -2.86172877, -1.59384208]])

In [23]:
a+b.T

array([[ 0.38760611,  0.83749709,  1.61100753, -0.43527987],
       [-1.81674181, -0.43566607,  0.06609434, -2.86172877],
       [-1.21057778, -0.52312824,  0.97871968, -1.59384208]])

In [26]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c1 = a*b

In [27]:
c1.shape

(3, 3)

In [29]:
a

array([[-1.16471288, -0.39771371, -0.27152631],
       [-1.26031323, -1.08025946,  0.26914347],
       [-0.85531774, -1.02192831,  0.31048439]])

In [30]:
b

array([[1.46493893],
       [0.56994947],
       [0.3821899 ]])

In [28]:
c1

array([[-1.70623324, -0.5826263 , -0.39776946],
       [-0.71831486, -0.6156933 ,  0.15339818],
       [-0.3268938 , -0.39057068,  0.118664  ]])

In [60]:
a2 = np.random.randn(1, 4)
b2 = np.random.randn(4, 1)
c2 = np.dot(a2,b2)

In [61]:
a2

array([[-1.3498996 ,  1.00797504, -1.08001167, -1.68512549]])

In [62]:
b2

array([[ 0.14225447],
       [-0.37223263],
       [ 0.03768954],
       [-0.118639  ]])

In [63]:
c2

array([[-0.408014]])

In [65]:
64*64*3

12288

In [ ]:
reshape(num_px*num_px*3, m_train)